CREATE TYPE [dbo].[AllTypesNull] AS TABLE
(
  -- Don't include rowversion/timestamp because they're not useful in TVPs
  [bigint] BIGINT NULL,
  [binary] BINARY(42) NULL,
  [bit] BIT NULL,
  [char] CHAR(42) NULL,
  [date] DATE NULL,
  [datetime] DATETIME NULL,
  [datetime2] DATETIME2(3) NULL,
  [datetimeoffset] DATETIMEOFFSET(1) NULL,
  [decimal] DECIMAL(10, 5) NULL,
  [float] FLOAT(42) NULL,
  [image] IMAGE NULL,
  [int] INT NULL,
  [money] MONEY NULL,
  [nchar] NCHAR(42) NULL,
  [ntext] NTEXT NULL,
  [numeric] NUMERIC(8, 3) NULL,
  [nvarchar] NVARCHAR(42) NULL,
  [real] REAL NULL,
  [smalldatetime] SMALLDATETIME NULL,
  [smallint] SMALLINT NULL,
  [smallmoney] SMALLMONEY NULL,
  [text] TEXT NULL,
  [time] TIME(1) NULL,
  [tinyint] TINYINT NULL,
  [uniqueidentifier] UNIQUEIDENTIFIER NULL,
  [varbinary] VARBINARY(42) NULL,
  [varchar] VARCHAR(42) NULL,
  [xml] XML NULL
)
