CREATE TABLE #AllTypesNonNull (
  [Bigint] BIGINT NOT NULL,
  [Binary] BINARY(42) NOT NULL,
  [Bit] BIT NOT NULL,
  [Char] CHAR(42) NOT NULL,
  [Date] DATE NOT NULL,
  [Datetime] DATETIME NOT NULL,
  [Datetime2] DATETIME2(3) NOT NULL,
  [Datetimeoffset] DATETIMEOFFSET(1) NOT NULL,
  [Decimal] DECIMAL(10, 5) NOT NULL,
  [Float] FLOAT(42) NOT NULL,
  [Image] IMAGE NOT NULL,
  [Int] INT NOT NULL,
  [Money] MONEY NOT NULL,
  [Nchar] NCHAR(42) NOT NULL,
  [Ntext] NTEXT NOT NULL,
  [Numeric] NUMERIC(8, 3) NOT NULL,
  [Nvarchar] NVARCHAR(42) NOT NULL,
  [Real] REAL NOT NULL,
  [Smalldatetime] SMALLDATETIME NOT NULL,
  [Smallint] SMALLINT NOT NULL,
  [Smallmoney] SMALLMONEY NOT NULL,
  [Text] TEXT NOT NULL,
  [Time] TIME(1) NOT NULL,
  [Tinyint] TINYINT NOT NULL,
  [Uniqueidentifier] UNIQUEIDENTIFIER NOT NULL,
  [Varbinary] VARBINARY(42) NOT NULL,
  [Varchar] VARCHAR(42) NOT NULL,
  [Xml] XML NOT NULL
)
