CREATE PROCEDURE [dbo].[ProcWithAllTypesExtended]
  @bigint BIGINT,
  @binary BINARY(42),
  @bit BIT,
  @char CHAR(42),
  @date DATE,
  @datetime DATETIME,
  @datetime2 DATETIME2(3),
  @datetimeoffset DATETIMEOFFSET(1),
  @decimal DECIMAL(10, 5),
  @float FLOAT(42),
  @image IMAGE,
  @int INT,
  @money MONEY,
  @nchar NCHAR(42),
  @ntext NTEXT,
  @numeric NUMERIC(8, 3),
  @nvarchar NVARCHAR(42),
  @real REAL,
  @rowversion ROWVERSION,
  @smalldatetime SMALLDATETIME,
  @smallint SMALLINT,
  @smallmoney SMALLMONEY,
  @text TEXT,
  @time TIME(1),
  @timestamp TIMESTAMP,
  @tinyint TINYINT,
  @uniqueidentifier UNIQUEIDENTIFIER,
  @varbinary VARBINARY(42),
  @varchar VARCHAR(42),
  @xml XML
AS

-- Use an extended sproc to force sp_describe_first_result_set to fail
-- and parser to fallback to SET FMTONLY ON
EXEC sp_getapplock 'TestLock', 'Update'

SELECT
  [bigint] = @bigint,
  [binary] = @binary,
  [bit] = @bit,
  [char] = @char,
  [date] = @date,
  [datetime] = @datetime,
  [datetime2] = @datetime2,
  [datetimeoffset] = @datetimeoffset,
  [decimal] = @decimal,
  [float] = @float,
  [image] = @image,
  [int] = @int,
  [money] = @money,
  [nchar] = @nchar,
  [ntext] = @ntext,
  [numeric] = @numeric,
  [nvarchar] = @nvarchar,
  [real] = @real,
  [rowversion] = @rowversion,
  [smalldatetime] = @smalldatetime,
  [smallint] = @smallint,
  [smallmoney] = @smallmoney,
  [text] = @text,
  [time] = @time,
  [timestamp] = @timestamp,
  [tinyint] = @tinyint,
  [uniqueidentifier] = @uniqueidentifier,
  [varbinary] = @varbinary,
  [varchar] = @varchar,
  [xml] = @xml
