CREATE TABLE [dbo].[AllTypesNonNull]
(
  [key] INT NOT NULL PRIMARY KEY,
  [bigint] BIGINT NOT NULL,
  [binary] BINARY(42) NOT NULL,
  [bit] BIT NOT NULL,
  [char] CHAR(42) NOT NULL,
  [date] DATE NOT NULL,
  [datetime] DATETIME NOT NULL,
  [datetime2] DATETIME2(3) NOT NULL,
  [datetimeoffset] DATETIMEOFFSET(1) NOT NULL,
  [decimal] DECIMAL(10, 5) NOT NULL,
  [float] FLOAT(42) NOT NULL,
  [image] IMAGE NOT NULL,
  [int] INT NOT NULL,
  [money] MONEY NOT NULL,
  [nchar] NCHAR(42) NOT NULL,
  [ntext] NTEXT NOT NULL,
  [numeric] NUMERIC(8, 3) NOT NULL,
  [nvarchar] NVARCHAR(42) NOT NULL,
  [real] REAL NOT NULL,
  [smalldatetime] SMALLDATETIME NOT NULL,
  [smallint] SMALLINT NOT NULL,
  [smallmoney] SMALLMONEY NOT NULL,
  [text] TEXT NOT NULL,
  [time] TIME(1) NOT NULL,
  [tinyint] TINYINT NOT NULL,
  [uniqueidentifier] UNIQUEIDENTIFIER NOT NULL,
  [varbinary] VARBINARY(42) NOT NULL,
  [varchar] VARCHAR(42) NOT NULL,
  [xml] XML NOT NULL
)
