CREATE TABLE #AllTypesNull (
  [Bigint] BIGINT NULL,
  [Binary] BINARY(42) NULL,
  [Bit] BIT NULL,
  [Char] CHAR(42) NULL,
  [Date] DATE NULL,
  [Datetime] DATETIME NULL,
  [Datetime2] DATETIME2(3) NULL,
  [Datetimeoffset] DATETIMEOFFSET(1) NULL,
  [Decimal] DECIMAL(10, 5) NULL,
  [Float] FLOAT(42) NULL,
  [Image] IMAGE NULL,
  [Int] INT NULL,
  [Money] MONEY NULL,
  [Nchar] NCHAR(42) NULL,
  [Ntext] NTEXT NULL,
  [Numeric] NUMERIC(8, 3) NULL,
  [Nvarchar] NVARCHAR(42) NULL,
  [Real] REAL NULL,
  [Smalldatetime] SMALLDATETIME NULL,
  [Smallint] SMALLINT NULL,
  [Smallmoney] SMALLMONEY NULL,
  [Text] TEXT NULL,
  [Time] TIME(1) NULL,
  [Tinyint] TINYINT NULL,
  [Uniqueidentifier] UNIQUEIDENTIFIER NULL,
  [Varbinary] VARBINARY(42) NULL,
  [Varchar] VARCHAR(42) NULL,
  [Xml] XML NULL
)
